version: "3.7"
services:
  nameSrv:
    image: rocketmqinc/rocketmq
    container_name: rmqnamesrv
    restart: always
    ports:
    - 9876:9876
    volumes:
      - ./rocketmq/logs:/home/rocketmq/logs
      - ./rocketmq/store:/home/rocketmq/store
    command: sh mqnamesrv
  broker:
    image: rocketmqinc/rocketmq
    container_name: "rocket-broker"
    ports:
    - 10909:10909
    - 10911:10911
    - 10912:10912
    volumes:
      - ./rocketmq/logs:/home/rocketmq/logs
      - ./rocketmq/store:/home/rocketmq/store
      - ./broker.conf:/opt/rocketmq-4.4.0/conf/broker.conf
    command: sh mqbroker -n nameSrv:9876 -c ../conf/broker.conf
    depends_on:
      - nameSrv
    environment:
      - JAVA_HOME=/usr/lib/jvm/jre
  console:
    image: styletang/rocketmq-console-ng
    container_name: rocketmq-console-ng
    ports:
      - 8087:8080
    depends_on:
      - nameSrv
    environment:
      - JAVA_OPTS= -Dlogging.level.root=info   -Drocketmq.namesrv.addr=rmqnamesrv:9876
      - Dcom.rocketmq.sendMessageWithVIPChannel=false